# Generated by Django 3.2.8 on 2021-11-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='useful_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='useful_review_record',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('movie', '映画'), ('book', '本'), ('meal', '食事'), ('animal', '動物'), ('other', 'その他')], max_length=50),
        ),
    ]
