# Generated by Django 3.2.8 on 2021-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_auto_20211118_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='comment',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
