# Generated by Django 3.2.8 on 2021-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_auto_20211122_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='useful_review_record',
            field=models.TextField(default='None'),
        ),
    ]
